name: PacketTester
version: '${project.version}'
main: me.kiiya.packettester.PacketTester
author: Kiiya
description: PacketTester
api-version: 1.8
commands:
  vehicle:
    description: Summon an armor stand
    usage: /<command>
    aliases: [vh]
  dismount:
    description: Dismount from the vehicle
    usage: /<command>
    aliases: [dm]
  npc:
    description: Spawn an NPC
    usage: /<command>
    aliases: [n]
